core/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm
app_name = 'core'
urlpatterns = [
    path('', views.frontpage, name = 'frontpage'),
    path('searchpage/', views.searchpage, name = 'searchpage'),
    path('signup/', views.signup, name = 'signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('mangaByLikes/', views.mangaByLikes, name = 'mangaByLikes'),
    path('likedManga/', views.likedManga, name = 'likedManga'),
    path('mangaByUpdate/', views.mangaByUpdate, name = 'mangaByUpdate'),
    path('filterView/', views.filterView, name = 'filterView'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'core/frontpage.html'), name = 'logout'),
    path('<int:pk>/', views.mangaByTag, name = 'mangaByTag'),

]

manga/urls.py
from django.urls import path
from . import views
from core.views import author
from .models import Chapter
app_name = 'manga'
urlpatterns = [
    path('<int:pk>/', views.detail, name = 'detail'),
    path('like/<int:pk>', views.LikeView, name = 'like_manga'),
    path('author/<int:pk>', author, name = 'author')
]

mangareader/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import frontpage, searchpage
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('manga/', include('manga.urls')),
    path('readingPage/', include('readingPage.urls')),
    path('searchpage/', searchpage, name = 'searchpage'),

] + static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

readingPage/urls.py
from django.urls import path
from .views import readingPage
app_name = 'readingPage'
urlpatterns = [
    path('<int:pk>/', readingPage, name = 'readingPage'),
]

manga/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(default="", null=False)
    class Meta:
        ordering = ('name',)
    def __str__(self):  
        return self.name
    def get_absolute_url(self):
        return reverse("mangaByTag", kwargs={"slug": self.slug})
class Author(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(default="", null=False)
    def __str__(self) -> str:
        return self.name
    def get_absolute_url(self):
        return reverse("detail", kwargs={"slug": self.slug})
class Manga(models.Model):
    name = models.CharField(max_length=200,default ='')
    slug = models.SlugField(default="", null=False)
    tag = models.ManyToManyField(Tag, related_name='mangas', default='') 
    overlook = models.TextField(blank= True, null= True)
    author = models.ForeignKey(Author, related_name='author', on_delete=models.CASCADE, default='unknown')
    banner = models.ImageField(upload_to='manga_images', blank= True, null = True)
    cover = models.ImageField(upload_to = 'manga_images', blank= True, null = True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    like = models.ManyToManyField(User, related_name='like_manga', blank= True)
    views = models.IntegerField(default=0)
    def like_count(self):
        return self.like.count()
    def __str__(self) -> str:
        return self.name
    def get_absolute_url(self):
        return reverse("detail", kwargs={"slug": self.slug})
class Chapter(models.Model):
    name = models.IntegerField(default=0)
    manga = models.ForeignKey(Manga, on_delete=models.CASCADE, default=0, related_name='manga')
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    slug = models.SlugField(default="", null=False)
    user_visited = models.ManyToManyField(User, blank= True)
    def __str__(self) -> str:
        return str(self.name) + '-' +str(self.manga.name)
    class Meta:
        ordering = ["name"]
    def get_absolute_url(self):
        return reverse("detail", kwargs={"slug": self.slug})
class UserAction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    last_chaper = models.CharField(max_length=255)
    timestamp = models.DateTimeField(auto_now_add=True)

manga/views.py
from django.shortcuts import render, get_object_or_404
from .models import Manga, Tag,Chapter
from readingPage.models import Page
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User
# Create your views here.
def detail(request, pk):
    manga = get_object_or_404(Manga, pk=pk)
    tags = manga.tag.all()
    chapters = Chapter.objects.filter(manga=manga)
    manga.views += 1
    manga.save()
    liked = False
    last_chapter = chapters.all()[0]

    if request.user.is_authenticated:
        if len(chapters.filter(user_visited=request.user)) > 0:
            last_chapter = chapters.filter(user_visited=request.user).last()
        if manga.like.filter(id=request.user.id).exists():
            liked = True

    return render(request, 'manga/detail.html', {
        'manga': manga,
        'tags': tags,
        'chapters': chapters,
        'author': manga.author,
        'like_count': manga.like_count(),
        'liked': liked,
        'last_chapter': last_chapter
    })

def LikeView(request, pk):
    manga = get_object_or_404(Manga, id = request.POST.get('manga_id'))
    liked = False
    if manga.like.filter(id = request.user.id).exists():
        manga.like.remove(request.user)
        liked = False
    else:
        manga.like.add(request.user)
        liked = True

    return HttpResponseRedirect(reverse('manga:detail', args = [str(pk)]))

manga/templates/manga/detail.html
{% extends "core/base.html" %}

{% block title %}
    {{manga.name}}
{% endblock  %}

{% block content %}
<div class = "mw-100" style = "height: 20rem; background: #919191">
    <img src = "{{manga.cover.url}}" class="d-block h-100 w-100" style = "object-fit:cover"/>
</div>
<div class="container", style = "background-color: white">
  <div class="row">
    <div class = "col-sm-3" >
        <div class = "row">
            <img src = "{{manga.banner.url}}" class = "d-block h-100 w-100">
        </div>
        <br>
        <div class = "row">
            <div class = "d-flex justify-content-center">
                <div class = "col ">
                <form action = "{% url 'manga:like_manga' manga.id%}" method = "POST">
                    {% csrf_token %}
                    {% if user.is_authenticated %}
                        {% if liked %}
                        <button type = "submit", name = "manga_id", value = "{{manga.id}}" class ="btn btn-outline-dark" >Đã thích</button>
                        {% else %}
                        <button type = "submit", name = "manga_id", value = "{{manga.id}}" class ="btn btn-outline-dark" >Thích</button>
                        {% endif %}
                    {%else%}
                        <button type = "submit", name = "manga_id", value = "{{manga.id}}" class ="btn btn-outline-secondary" disabled >Thích</button>
                        <br/>
                        <small>Bạn cần đăng nhập để like</small>
                    {% endif%}
                </form>
                </div>
            </div>
        </div>
    </div>
    <div class = "col-6">
        <div class="d-flex justify-content-start"><h1>{{manga.name}}</h1>
        </div>
        <br/>
        <div class="d-flex justify-content-start">
            <p>Tác giả: <a class = " text-reset" href = "{%url 'manga:author' author.id%}">{{manga.author}}</a><br/><br/>
            Thể loại: {% for tag in tags %} <a class = "text-decoration-none"href = "{% url 'core:mangaByTag' tag.id%}"><button type="button" class="btn btn-outline-secondary">{{tag.name}}</button>
            </a>{% endfor %}<br/><br/>
            Số chương hiện có: {{chapters.count}}<br/>
            Số lượt xem <i class="fa-solid fa-eye"></i>: {{manga.views}}<br/>
            Số lượt thích <i class="fa-solid fa-thumbs-up"></i>:{{like_count}}
            <br/>
            {% csrf_token %}
            {% if user.is_authenticated %}
                {% if last_chapter.name > 1%}
                    Bạn đang đọc đến chương: <a href = '{% url "readingPage:readingPage" last_chapter.id %} ' class = 'text-reset'>{{last_chapter.name}}</a>
                {% else %}
                {% endif %}
            {% endif %}
            <br/>
            </p>
        </div>
        <br/>
        <div class="d-flex justify-content-start overflow-auto" style = "max-height: 200px">
            <p>Giới thiệu: <br>{{manga.overlook}}</p>
        </div>
    </div>
    
    <div class = "col-sm-3">
        <div class = "row">
                <h3> Danh sách chương </h3>
            </div>
            <div class = "row">
                {% for chapter in chapters %}
                    <div class = "row">
                        <a href = "{% url 'readingPage:readingPage' chapter.id %}" class = "d-flex justify-content-center text-reset "> Chương {{chapter.name}}</a>
                    </div>
                {% endfor %}
            </div>
    </div>
  </div>
</div>
{% endblock  %}