core/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm
app_name = 'core'
urlpatterns = [
    path('', views.frontpage, name = 'frontpage'),
    path('searchpage/', views.searchpage, name = 'searchpage'),
    path('signup/', views.signup, name = 'signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('mangaByLikes/', views.mangaByLikes, name = 'mangaByLikes'),
    path('likedManga/', views.likedManga, name = 'likedManga'),
    path('mangaByUpdate/', views.mangaByUpdate, name = 'mangaByUpdate'),
    path('filterView/', views.filterView, name = 'filterView'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'core/frontpage.html'), name = 'logout'),
    path('<int:pk>/', views.mangaByTag, name = 'mangaByTag'),

]

manga/urls.py
from django.urls import path
from . import views
from core.views import author
from .models import Chapter
app_name = 'manga'
urlpatterns = [
    path('<int:pk>/', views.detail, name = 'detail'),
    path('like/<int:pk>', views.LikeView, name = 'like_manga'),
    path('author/<int:pk>', author, name = 'author')
]

mangareader/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import frontpage, searchpage
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('manga/', include('manga.urls')),
    path('readingPage/', include('readingPage.urls')),
    path('searchpage/', searchpage, name = 'searchpage'),

] + static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'form-control',
        'id':'form2Example11'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'form-control',
        'id':'form2Example11'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'form-control',
        'id':'form2Example11'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'form-control',
        'id':'form2Example11'
    }))

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'form-control',
        'id':'form2Example11'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'id':"form2Example22",
        'class':"form-control"
    }))

core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from manga.models import Tag, Manga, Chapter, Author
from .forms import SignupForm
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
# Create your views here.
#Trang chủ
def frontpage(request):
    manga = Manga.objects.all()
    item_per_page = 10
    paginator = Paginator(manga, item_per_page)
    page = request.GET.get('page')
    try:
        manga = paginator.page(page)
    except PageNotAnInteger:
        manga = paginator.page(1)
    except EmptyPage:
        manga = paginator.page(paginator.num_pages)
    sorted_mangas = sorted(manga, key = lambda x: x.like_count(), reverse=True)
    most_viewed_manga = sorted_mangas.pop(0)
    tags = Tag.objects.all()
    chapters = Chapter.objects.all()
    return render(request, 'core/frontpage.html', {
        'mangas' : manga,
        'sorted_mangas': sorted_mangas,
        'most_viewed_manga' : most_viewed_manga,
    })
#tìm kiếm theo tên
def searchpage(request):
    if request.method == "POST":
        searched = request.POST['searched']
        mangas = Manga.objects.filter(name__contains = searched)
        item_per_page = 10
        paginator = Paginator(mangas, item_per_page)
        page = request.GET.get('page')
        try:
            mangas = paginator.page(page)
        except PageNotAnInteger:
            mangas = paginator.page(1)
        except EmptyPage:
            mangas = paginator.page(paginator.num_pages)
        return render(request, "core/searchpage.html", {
            'searched': searched,
            'mangas': mangas
        })
    return render(request, "core/searchpage.html", {

    })

#đăng kí 
def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form': form
    })
#Tab Truyện hot


def mangaByLikes(request):
    mangas = Manga.objects.all()
    mangas = sorted(mangas, key=lambda x: x.like_count(), reverse=True)
    items_per_page = 4
    paginator = Paginator(mangas, items_per_page)
    page = request.GET.get('page')
    try:
        mangas = paginator.page(page)
    except PageNotAnInteger:
        mangas = paginator.page(1)
    except EmptyPage:
        mangas = paginator.page(paginator.num_pages)
    return render(request, 'core/mangaByLikes.html', {
        'mangas': mangas
    })

#Danh sách truyện đã thích của user
@login_required
def likedManga(request):
    mangas = Manga.objects.filter(like=request.user)

    items_per_page = 10  # Đặt số item muốn hiển thị trên mỗi trang
    paginator = Paginator(mangas, items_per_page)
    page = request.GET.get('page')

    try:
        mangas = paginator.page(page)
    except PageNotAnInteger:
        mangas = paginator.page(1)
    except EmptyPage:
        mangas = paginator.page(paginator.num_pages)

    return render(request, 'core/likedManga.html', {
        'mangas': mangas
    })
#Tìm kiếm nâng cao

def filterView(request):
    tags = Tag.objects.all()
    mangas = Manga.objects.all()
    name_contains_query = request.GET.get('name_contains')
    author_query = request.GET.get('author')
    tag_list = request.GET.getlist('tags')
    sort = request.GET.get('sort')

    if name_contains_query != '' and name_contains_query is not None:
        mangas = mangas.filter(name__icontains=name_contains_query)
    if author_query != '' and author_query is not None:
        mangas = mangas.filter(author__name__icontains=author_query)
    if len(tag_list) > 0:
        for tag in tag_list:
            mangas = mangas.filter(tag__name__icontains=tag)
    if sort == 'A-Z':
        mangas = mangas.order_by('name')
    elif sort == 'Z-A':
        mangas = mangas.order_by('-name')
    elif sort == 'Ngày Cập Nhật Giảm Dần':
        mangas = mangas.order_by('-updated')
    elif sort == 'Ngày Cập Nhật Tăng Dần':
        mangas = mangas.order_by('updated')
    elif sort == 'Lượt Thích Giảm Dần':
        mangas = sorted(mangas, key=lambda x: x.like_count(), reverse=True)
    elif sort == 'Lượt Thích Tăng Dần':
        mangas = sorted(mangas, key=lambda x: x.like_count())
    elif sort == 'Lượt Xem Giảm Dần':
        mangas = sorted(mangas, key=lambda x: x.views, reverse=True)
    elif sort == 'Lượt Xem Tăng Dần':
        mangas = sorted(mangas, key=lambda x: x.views)
    items_per_page = 10  # Đặt số item muốn hiển thị trên mỗi trang
    paginator = Paginator(mangas, items_per_page)
    page = request.GET.get('page')

    try:
        mangas = paginator.page(page)
    except PageNotAnInteger:
        mangas = paginator.page(1)
    except EmptyPage:
        mangas = paginator.page(paginator.num_pages)

    return render(request, 'core/filterView.html', {
        'tags': tags,
        'mangas': mangas,
    })
def mangaByTag(request, pk):
    tag = get_object_or_404(Tag, id=pk)
    mangas = Manga.objects.filter(tag=tag)
    items_per_page = 10  # Đặt số item muốn hiển thị trên mỗi trang
    paginator = Paginator(mangas, items_per_page)
    page = request.GET.get('page')

    try:
        mangas = paginator.page(page)
    except PageNotAnInteger:
        mangas = paginator.page(1)
    except EmptyPage:
        mangas = paginator.page(paginator.num_pages)

    return render(request, 'core/mangaByTag.html', {
        'tag': tag,
        'mangas': mangas
    })
def mangaByUpdate(request):
    mangas = Manga.objects.all().order_by('-updated')

    items_per_page = 10  # Đặt số item muốn hiển thị trên mỗi trang
    paginator = Paginator(mangas, items_per_page)
    page = request.GET.get('page')

    try:
        mangas = paginator.page(page)
    except PageNotAnInteger:
        mangas = paginator.page(1)
    except EmptyPage:
        mangas = paginator.page(paginator.num_pages)

    return render(request, 'core/mangaByUpdate.html', {
        'mangas': mangas
    })
def author(request, pk):
    author = get_object_or_404(Author, pk = pk)
    mangas = Manga.objects.all().filter(author = author)
    item_per_page = 10
    paginator = Paginator(mangas, item_per_page)
    page = request.GET.get('page')
    try:
        mangas = paginator.page(page)
    except PageNotAnInteger:
        mangas = paginator.page(1)
    except EmptyPage:
        mangas = paginator.page(paginator.num_pages)
    mangas = Manga.objects.filter(author = author)
    return render(request, 'core/author.html',{
        'author': author,
        'mangas': mangas
    })

core/templates/core/author.html
{% extends "core/base.html" %}

{% block titile %}{{author.name}}{% endblock titile %}

{% block content %}
<h2 class="mb-12 text-2xl text-center">Truyện cùng tác giả {{author.name}}</h2>
<div class="container" style="background-color: white">
    <div class="container">
        <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3">
            {% for manga in mangas %}
                <div class="col justify-content-center d-flex">
                    <a class="text-reset text-decoration-none" href="{% url 'manga:detail' manga.id %}">
                        <div>
                            <img src="{{ manga.banner.url }}" class="rounded-t-xl" width="140" height="200">
                        </div>
                        <p style = 'font-size: 20px; text-align: center'>{{ manga.name }}</p>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
<div class="container text-center d-flex justify-content-center">
    <ul class="pagination">
        {% if mangas.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1" aria-label="First">
                    <span aria-hidden="true">&laquo;&laquo;</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ mangas.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}

        <li class="page-item disabled">
            <span class="page-link">Trang {{ mangas.number }} / {{ mangas.paginator.num_pages }}</span>
        </li>

        {% if mangas.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ mangas.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ mangas.paginator.num_pages }}" aria-label="Last">
                    <span aria-hidden="true">&raquo;&raquo;</span>
                </a>
            </li>
        {% endif %}
    </ul>
</div>

</div>

{% endblock content %}

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %}{% endblock  %}|WEBSITENAME</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
  <style>
  .fa-lg{
    line-height: 1.2em!important;
    font-size:1.2em!important
  }
  .py-5{
    padding-top:0!important
  }
  .gradient-form{
    height: 0!important
  }
  .gradient-custom-2 {
    background: linear-gradient(112.1deg, rgb(32, 38, 57) 11.4%, rgb(63, 76, 119) 70.2%);
    }

    @media (min-width: 768px) {
      .gradient-form {
        height: 100vh !important;
      }
    }
    @media (min-width: 769px) {
      .gradient-custom-2 {
        border-top-right-radius: .3rem;
        border-bottom-right-radius: .3rem;
      }
    }
    .top {
      --offset: 50px; 

      position: sticky;
      bottom: 20px;      
      margin-right: 10px; 
      place-self: end;
      margin-top: calc(100vh + var(--offset))
    }
    .carousel-item{
      height: 24rem;
      background: linear-gradient(112.1deg, rgb(32, 38, 57) 11.4%, rgb(63, 76, 119) 70.2%);    
    }
    .col-cover{
      height: 20rem;
      background-color: #919191;
    }
    .banner{
      border: 2px solid #555;
    }
    .row-detail{
      height: 10rem;
    }
    html, body{
      background-color: #e6e6e6;
      height:100%;
      margin:0;
      padding:0;
    }
    #body {
      padding-bottom:60px;
      display: flex;
      flex-direction: column; 
    }
    #header {
    }
    #footer {
      margin-top: auto;
      bottom:0;
      width:100%;
      height:auto;
    }
    #container {
      min-height:100%;
      position:relative;
    }
    
  </style>
</head> 
<body>
<div id="container">
  <div id = "header " class = "sticky-top">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'core:frontpage' %}">Trang Chủ</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'core:mangaByLikes'%}">Truyện Hot</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{%url 'core:mangaByUpdate' %}">Truyện Mới Cập Nhật</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'core:filterView'%}">Bộ Lọc</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-expanded="true">
                Thể Loại
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                {% for tag in tags  %}
                    <li><a class="dropdown-item" href="{% url 'core:mangaByTag' tag.id  %}">{{tag.name}}</a></li>
                {% endfor %}
              </ul>
            </li>
          </ul>
          <form class="d-flex" action="{% url 'searchpage' %}" method = POST>
            {% csrf_token %}
                <input class="form-control me-2" type="search" placeholder="Tìm kiếm truyện" name = "searched" aria-label="Search">
                <button class="btn btn-outline-success btn-outline-light" type="submit">Tìm</button>
          </form>
        </div>
          <ul class="navbar-nav ">
          {% if request.user.is_authenticated %}
            <li class="nav-item nav">
              <a href="{%url 'core:likedManga' %}" class = "nav-link " aria-current="page" > Truyện Đã Thích</a>
            </li>
            <li class="nav-item">
              <li><a href="{%url 'core:logout' %}" class = "nav-link " aria-current="page"> Log out</a></li>
            </li>
            {% else %}
            <li class="nav-item">
              <a href="{%url 'core:signup' %}" class = "nav-link " aria-current="page" >Sign Up</a>
            </li>
            <li class="nav-item">
              <li><a href="{% url 'core:login' %}" class = "nav-link " aria-current="page"> Log in</a></li>
            </li>
          {% endif %}
          </ul>
      </div>
    </nav>
  </div>
  <div id="body">
      {% block content %}

      {% endblock content %}
  </div>
  </div>
</div>
<footer class="bg-dark text-center text-white ">
  <div class="container p-4 pb-0">
    <section class="mb-4">
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-twitter"></i
      ></a>

      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-google"></i
      ></a>

      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-instagram"></i
      ></a>

      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-linkedin-in"></i
      ></a>

      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-github"></i
      ></a>
    </section>
  </div>

  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2023 Copyright:
    <a class="text-white" href="#">Nhóm 17 Python</a>
  </div>
</footer>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

core/templates/core/filterView.html
{% extends "core/base.html" %}
{% block title %}
Tim kiem nang cao
{% endblock title %}

{% block content %}
<div class = "container">
    <form>
    <div class="form-row">
        <div class="form-group col-md-6">
        <label for="inputEmail4">Tên Truyện</label>
        <input type="search" class="form-control" id="inputEmail4" placeholder="Tên Truyện" name = 'name_contains'>
        </div>
        <div class="form-group col-md-6">
        <label for="inputPassword4">Tác Giả</label>
        <input type="search" class="form-control" id="inputPassword4" placeholder="Tác Giả" name = 'author'>
        </div>
    </div>

    <div class="form-row">
            <div class="form-group col-md-4">
            <label for="inputState"></label>
            <select id="inputState" class="form-control" name = 'sort'>
                <option selected>Sắp xếp theo</option>
                <option>A-Z</option>
                <option>Z-A</option>
                <option>Ngày Cập Nhật Tăng Dần</option>
                <option>Ngày Cập Nhật Giảm Dần</option>
                <option>Lượt Thích Tăng Dần</option>
                <option>Luot Thích Giảm Dần</option>
                <option>Lượt Xem Tăng Dần</option>
                <option>Lượt Xem Giảm Dần</option>
            </select>
            </div>
    </div>

    <div class="form-check container">
        <div class = "row row-cols-6">
            {% for tag in tags  %}
                <div class = "column">
                <input class="form-check-input" type="checkbox" id="check{{tag.id}}" name="tags" value="{{tag.name}}" unchecked>
                <label class="form-check-label">{{tag.name}}</label>
                </div>
            {% endfor %}
        </div>
    
        
    </div>
    <button type="submit" class="btn btn-dark">Tìm kiếm</button>
    </form>
</div>
<h2 class="mb-12 text-2xl text-center">Kết quả tìm kiếm</h2>
<div class="container" style="background-color: white">
    <div class="container">
        <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3">
            {% for manga in mangas %}
                <div class="col justify-content-center d-flex">
                    <a class="text-reset text-decoration-none" href="{% url 'manga:detail' manga.id %}">
                        <div>
                            <img src="{{ manga.banner.url }}" class="rounded-t-xl" width="140" height="200">
                        </div>
                        <p style = 'font-size: 20px; text-align: center'>{{ manga.name }}</p>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
<div class="container text-center d-flex justify-content-center">
    <ul class="pagination">
        {% if mangas.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1" aria-label="First">
                    <span aria-hidden="true">&laquo;&laquo;</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ mangas.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}

        <li class="page-item disabled">
            <span class="page-link">Trang {{ mangas.number }} / {{ mangas.paginator.num_pages }}</span>
        </li>

        {% if mangas.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ mangas.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ mangas.paginator.num_pages }}" aria-label="Last">
                    <span aria-hidden="true">&raquo;&raquo;</span>
                </a>
            </li>
        {% endif %}
    </ul>
</div>

</div>

{% endblock content %}

core/templates/core/frontpage.html
{% extends "core/base.html" %}
{% block title %}Home{% endblock  %}
{% block content %}
<div id="carouselExampleIndicators" class="carousel slide " data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active d-block w-100 d-flex justify-content-center">
      <img src="{{most_viewed_manga.cover.url}}" class="d-block h-100 w-100 banner" style = "object-fit:contain"/>
    </div>
    {% for manga in sorted_mangas %}
    <div class="carousel-item">
      <img src="{{manga.cover.url}}" class="d-block w-100 h-100 banner" style = "object-fit:contain"/>
    </div>
    {% endfor %}
  </div>
  <button class="carousel-control-prev" type="button" data-target="#carouselExampleIndicators" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only"></span>
  </button>
  <button class="carousel-control-next" type="button" data-target="#carouselExampleIndicators" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only"></span>
  </button>
</div>

<h2 class="mb-12 text-2xl text-center">Tất cả truyện</h2>
<div class="container" style="background-color: white">
    <div class="container">
        <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3">
            {% for manga in mangas %}
                <div class="col justify-content-center d-flex">
                    <a class="text-reset text-decoration-none" href="{% url 'manga:detail' manga.id %}">
                        <div>
                            <img src="{{ manga.banner.url }}" class="rounded-t-xl" width="140" height="200">
                        </div>
                        <p style = 'font-size: 20px; text-align: center'>{{ manga.name }}</p>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
<div class="container text-center d-flex justify-content-center">
    <ul class="pagination">
        {% if mangas.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1" aria-label="First">
                    <span aria-hidden="true">&laquo;&laquo;</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ mangas.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}

        <li class="page-item disabled">
            <span class="page-link">Trang {{ mangas.number }} / {{ mangas.paginator.num_pages }}</span>
        </li>

        {% if mangas.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ mangas.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ mangas.paginator.num_pages }}" aria-label="Last">
                    <span aria-hidden="true">&raquo;&raquo;</span>
                </a>
            </li>
        {% endif %}
    </ul>
</div>

</div>


{% endblock  %}

core/templates/core/likedManga.html
{% extends "core/base.html" %}
{% block title %}
Truyện Đã Thích
{% endblock title %}    
{% block content %}
<h2 class="mb-12 text-2xl text-center">Truyện đã thích</h2>
<div class="container" style="background-color: white">
    <div class="container">
        <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3">
            {% for manga in mangas %}
                <div class="col justify-content-center d-flex">
                    <a class="text-reset text-decoration-none" href="{% url 'manga:detail' manga.id %}">
                        <div>
                            <img src="{{ manga.banner.url }}" class="rounded-t-xl" width="140" height="200">
                        </div>
                        <p style = 'font-size: 20px; text-align: center'>{{ manga.name }}</p>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
<div class="container text-center d-flex justify-content-center">
    <ul class="pagination">
        {% if mangas.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1" aria-label="First">
                    <span aria-hidden="true">&laquo;&laquo;</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ mangas.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}

        <li class="page-item disabled">
            <span class="page-link">Trang {{ mangas.number }} / {{ mangas.paginator.num_pages }}</span>
        </li>

        {% if mangas.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ mangas.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ mangas.paginator.num_pages }}" aria-label="Last">
                    <span aria-hidden="true">&raquo;&raquo;</span>
                </a>
            </li>
        {% endif %}
    </ul>
</div>

</div>
{% endblock content %}